spring.application.name=OICR
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

ocr.space.api.url=https://api.ocr.space/parse/image
ocr.space.api.key=${OCR_SPACE_API_KEY:}
